#!/usr/bin/env python3
"""Ingest generated intervertebral disc OBJ files into the atlas bundles.

This script:
1. Reads OBJ files generated by generate_intervertebral_discs.py
2. Loads existing manifests for ct_vhm and ct_vhf
3. Adds new mesh entries for each disc
4. Updates the manifests with proper vertex/triangle offsets
5. Consolidates all meshes into bundle files
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from collections import defaultdict

import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from engine import vh_ingest as vh

OUTPUT_DIR = REPO_ROOT / "data" / "ct_sources" / "task_outputs"
BUILD_DIR = REPO_ROOT / "build" / "vh"


def read_obj_file(filepath: Path) -> tuple[np.ndarray, np.ndarray]:
    """Read OBJ file and return vertices and faces.

    Returns:
        (vertices [N, 3], faces [M, 3])
    """
    vertices = []
    faces = []

    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue

            parts = line.split()
            if not parts:
                continue

            if parts[0] == 'v':  # Vertex
                v = [float(parts[1]), float(parts[2]), float(parts[3])]
                vertices.append(v)
            elif parts[0] == 'f':  # Face
                # Handle different face formats (v, v/t, v/t/n, v//n)
                face_indices = []
                for part in parts[1:]:
                    # Extract vertex index (always first)
                    v_idx = int(part.split('/')[0]) - 1  # OBJ uses 1-indexing
                    face_indices.append(v_idx)

                # Triangulate if necessary
                for i in range(1, len(face_indices) - 1):
                    faces.append([face_indices[0], face_indices[i], face_indices[i + 1]])

    if not vertices or not faces:
        raise ValueError(f"No vertices or faces found in {filepath}")

    return np.array(vertices), np.array(faces)


def load_manifest(subject: str) -> dict:
    """Load manifest for a subject."""
    manifest_path = BUILD_DIR / subject / "manifest.json"
    with open(manifest_path) as f:
        return json.load(f)


def save_manifest(subject: str, manifest: dict) -> None:
    """Save manifest for a subject."""
    manifest_path = BUILD_DIR / subject / "manifest.json"
    with open(manifest_path, 'w') as f:
        json.dump(manifest, f, indent=2)


def consolidate_geometry(subject: str, disc_meshes: dict[str, tuple]) -> tuple[np.ndarray, np.ndarray]:
    """Consolidate existing geometry with new disc meshes.

    Returns:
        (consolidated_vertices, consolidated_faces)
    """
    manifest = load_manifest(subject)
    subject_dir = BUILD_DIR / subject

    # Load existing mesh from binary file
    mesh_file = subject_dir / f"{subject}.bin"
    if not mesh_file.exists():
        raise SystemExit(f"Mesh file not found: {mesh_file}")

    # Read existing binary mesh
    existing_verts, existing_faces = vh.read_indexed_mesh(mesh_file)

    # Combine with new discs
    all_vertices = [existing_verts]
    all_faces = [existing_faces]

    for atlas_id, (verts, faces) in sorted(disc_meshes.items()):
        all_vertices.append(verts)
        all_faces.append(faces)

    # Consolidate with proper offsets
    consolidated_verts = np.vstack(all_vertices)

    vertex_offset = 0
    consolidated_faces = []
    for verts, faces in zip(all_vertices, all_faces):
        offset_faces = faces + vertex_offset
        consolidated_faces.append(offset_faces)
        vertex_offset += len(verts)

    consolidated_faces = np.vstack(consolidated_faces)

    return consolidated_verts, consolidated_faces


def cmd_ingest(args: argparse.Namespace) -> int:
    """Ingest disc OBJ files into bundles."""

    for subject in ["ct_vhm", "ct_vhf"]:
        print(f"\nIngesting discs for {subject}...")
        subject_dir = BUILD_DIR / subject

        # Load manifest
        manifest = load_manifest(subject)
        existing_structures = {s["atlas_id"]: s for s in manifest["structures"]}

        # Load existing mesh to get current vertex/triangle counts
        mesh_file = subject_dir / f"{subject}.bin"
        if mesh_file.exists():
            existing_verts, existing_faces = vh.read_indexed_mesh(mesh_file)
            vertex_offset = len(existing_verts)
            face_offset = len(existing_faces)
        else:
            vertex_offset = 0
            face_offset = 0
            existing_verts = np.empty((0, 3))
            existing_faces = np.empty((0, 3), dtype=int)

        # Load all disc OBJ files for this subject
        disc_meshes = {}
        for obj_file in sorted(OUTPUT_DIR.glob(f"{subject}_intervertebral_disc_*.obj")):
            # Extract atlas_id from filename
            # Format: ct_vhm_intervertebral_disc_c1_c2.obj
            parts = obj_file.stem.split('_', 2)  # Split on first 2 underscores
            atlas_id = '_'.join(parts[2:])  # Get everything after "ct_vhm_"

            try:
                verts, faces = read_obj_file(obj_file)
                disc_meshes[atlas_id] = (verts, faces)
                print(f"  Loaded {obj_file.name}: {len(verts)} verts, {len(faces)} faces")
            except Exception as e:
                print(f"  Error loading {obj_file.name}: {e}")
                continue

        if not disc_meshes:
            print(f"  No disc files found for {subject}")
            continue

        # Build new consolidated mesh
        all_vertices = [existing_verts]
        all_faces = [existing_faces]
        new_structures = []

        running_vertex_offset = vertex_offset
        running_face_offset = face_offset

        for atlas_id in sorted(disc_meshes.keys()):
            verts, faces = disc_meshes[atlas_id]

            # Compute bounding box
            bbox_min = verts.min(axis=0)
            bbox_max = verts.max(axis=0)

            # Add to consolidation
            all_vertices.append(verts)
            all_faces.append(faces)

            # Create new structure entry
            struct = {
                "atlas_id": atlas_id,
                "source_structure": atlas_id,
                "side": None,
                "source_file": f"generated by generate_intervertebral_discs.py#{atlas_id}",
                "vertex_offset": running_vertex_offset,
                "face_offset": running_face_offset,
                "vertex_count": len(verts),
                "triangle_count": len(faces),
                "bbox_min_mm": bbox_min.tolist(),
                "bbox_max_mm": bbox_max.tolist(),
                "tris_full_at_source": len(faces),
            }
            new_structures.append(struct)

            running_vertex_offset += len(verts)
            running_face_offset += len(faces)

        # Consolidate meshes
        consolidated_verts = np.vstack(all_vertices)
        consolidated_faces = np.vstack(all_faces)

        # Save consolidated mesh
        mesh_file = subject_dir / f"{subject}.bin"
        vh.write_indexed_mesh(mesh_file, consolidated_verts, consolidated_faces)
        print(f"  Wrote {mesh_file}: {len(consolidated_verts)} vertices, {len(consolidated_faces)} faces")

        # Update manifest
        manifest["structures"].extend(new_structures)
        manifest["vertex_count"] = len(consolidated_verts)
        manifest["triangle_count"] = len(consolidated_faces)
        manifest["bbox_min_mm"] = consolidated_verts.min(axis=0).tolist()
        manifest["bbox_max_mm"] = consolidated_verts.max(axis=0).tolist()

        save_manifest(subject, manifest)
        print(f"  Updated manifest with {len(new_structures)} new disc structures")
        print(f"  Total structures: {len(manifest['structures'])}")

    print("\nIngest complete. Re-export viewer bundles now with:")
    print("  python3 scripts/export_viewer_bundle.py --male --female")

    return 0


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "command",
        choices=["ingest"],
        help="Command to run",
    )

    args = parser.parse_args()

    if args.command == "ingest":
        return cmd_ingest(args)

    return 0


if __name__ == "__main__":
    sys.exit(main())
