#!/usr/bin/env python3
"""Ingest generated intervertebral disc OBJ files into the atlas bundles.

This script:
1. Reads OBJ files generated by generate_intervertebral_discs.py
2. Loads existing manifests for ct_vhm and ct_vhf
3. Removes any existing disc structures
4. Reconstructs mesh without discs
5. Adds new disc structures and mesh geometry
6. Updates manifests with proper vertex/triangle offsets
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

OUTPUT_DIR = REPO_ROOT / "data" / "ct_sources" / "task_outputs"
BUILD_DIR = REPO_ROOT / "build" / "vh"


def read_obj_file(filepath: Path) -> tuple[np.ndarray, np.ndarray]:
    """Read OBJ file and return vertices and faces."""
    vertices = []
    faces = []

    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue

            parts = line.split()
            if not parts:
                continue

            if parts[0] == 'v':  # Vertex
                v = [float(parts[1]), float(parts[2]), float(parts[3])]
                vertices.append(v)
            elif parts[0] == 'f':  # Face
                face_indices = []
                for part in parts[1:]:
                    v_idx = int(part.split('/')[0]) - 1
                    face_indices.append(v_idx)

                for i in range(1, len(face_indices) - 1):
                    faces.append([face_indices[0], face_indices[i], face_indices[i + 1]])

    return np.array(vertices), np.array(faces)


def read_mesh_binary(subject_dir: Path) -> tuple[np.ndarray, np.ndarray]:
    """Read existing mesh from binary files."""
    verts_file = subject_dir / "vertices.f32"
    faces_file = subject_dir / "faces.u32"

    if not verts_file.exists() or not faces_file.exists():
        return np.empty((0, 3)), np.empty((0, 3), dtype=np.uint32)

    verts = np.fromfile(verts_file, dtype=np.float32).reshape(-1, 3)
    faces = np.fromfile(faces_file, dtype=np.uint32).reshape(-1, 3)

    return verts, faces


def write_mesh_binary(subject_dir: Path, vertices: np.ndarray, faces: np.ndarray) -> None:
    """Write mesh to binary files."""
    vertices.astype(np.float32).tofile(subject_dir / "vertices.f32")
    faces.astype(np.uint32).tofile(subject_dir / "faces.u32")


def load_manifest(subject: str) -> dict:
    """Load manifest for a subject."""
    manifest_path = BUILD_DIR / subject / "manifest.json"
    with open(manifest_path) as f:
        return json.load(f)


def save_manifest(subject: str, manifest: dict) -> None:
    """Save manifest for a subject."""
    manifest_path = BUILD_DIR / subject / "manifest.json"
    with open(manifest_path, 'w') as f:
        json.dump(manifest, f, indent=2)


def cmd_ingest(args: argparse.Namespace) -> int:
    """Ingest disc OBJ files into bundles."""

    for subject in ["ct_vhm", "ct_vhf"]:
        print(f"\nIngesting discs for {subject}...")
        subject_dir = BUILD_DIR / subject

        # Load manifest and existing mesh
        manifest = load_manifest(subject)
        existing_verts, existing_faces = read_mesh_binary(subject_dir)

        print(f"  Current mesh: {len(existing_verts)} vertices, {len(existing_faces)} faces")
        print(f"  Current structures: {len(manifest['structures'])}")

        # Remove existing disc structures
        old_disc_count = len([s for s in manifest["structures"] if "intervertebral_disc" in s["atlas_id"]])
        if old_disc_count > 0:
            print(f"  Removing {old_disc_count} existing disc structures...")
            manifest["structures"] = [s for s in manifest["structures"] if "intervertebral_disc" not in s["atlas_id"]]

        # Rebuild mesh without discs by extracting non-disc geometry
        non_disc_verts = []
        non_disc_faces = []

        new_vertex_offset = 0
        new_face_offset = 0

        for struct in manifest["structures"]:
            old_vert_start = struct["vertex_offset"]
            old_vert_end = old_vert_start + struct["vertex_count"]
            old_face_start = struct["face_offset"]
            old_face_end = old_face_start + struct["triangle_count"]

            # Extract this structure's geometry
            struct_verts = existing_verts[old_vert_start:old_vert_end]
            struct_faces = existing_faces[old_face_start:old_face_end]

            # Remap face indices
            struct_faces_remapped = struct_faces + (new_vertex_offset - old_vert_start)

            # Update structure offsets
            struct["vertex_offset"] = new_vertex_offset
            struct["face_offset"] = new_face_offset

            non_disc_verts.append(struct_verts)
            non_disc_faces.append(struct_faces_remapped)

            new_vertex_offset += len(struct_verts)
            new_face_offset += len(struct_faces)

        # Consolidate non-disc geometry
        if non_disc_verts and non_disc_faces:
            consolidated_verts = np.vstack(non_disc_verts)
            consolidated_faces = np.vstack(non_disc_faces)
        else:
            consolidated_verts = np.empty((0, 3), dtype=np.float32)
            consolidated_faces = np.empty((0, 3), dtype=np.uint32)

        print(f"  Rebuilt mesh: {len(consolidated_verts)} vertices, {len(consolidated_faces)} faces")

        # Load disc OBJ files
        disc_meshes = {}
        for obj_file in sorted(OUTPUT_DIR.glob(f"{subject}_intervertebral_disc_*.obj")):
            stem = obj_file.stem
            atlas_id = stem.replace(f"{subject}_", "")

            try:
                verts, faces = read_obj_file(obj_file)
                disc_meshes[atlas_id] = (verts, faces)
            except Exception as e:
                print(f"  Error loading {obj_file.name}: {e}")
                continue

        if not disc_meshes:
            print(f"  No disc files found for {subject}")
            continue

        print(f"  Loaded {len(disc_meshes)} new disc structures")

        # Add discs to mesh
        all_vertices = [consolidated_verts] if len(consolidated_verts) > 0 else []
        all_faces = [consolidated_faces] if len(consolidated_faces) > 0 else []

        vertex_offset = len(consolidated_verts)
        face_offset = len(consolidated_faces)

        new_disc_structures = []

        for atlas_id in sorted(disc_meshes.keys()):
            verts, faces = disc_meshes[atlas_id]

            # Compute bounding box
            bbox_min = verts.min(axis=0)
            bbox_max = verts.max(axis=0)

            # Add to consolidation
            # BUG FIX (Q107): faces read from the OBJ file are 0-based LOCAL indices;
            # they must be shifted by this structure's own vertex_offset before being
            # appended to the shared global vertex/face arrays, or they silently
            # reference whatever structure happens to occupy the start of the array.
            all_vertices.append(verts)
            all_faces.append(faces + vertex_offset)

            # Create structure entry
            struct = {
                "atlas_id": atlas_id,
                "source_structure": atlas_id,
                "side": None,
                "source_file": f"generated by generate_intervertebral_discs.py#{atlas_id}",
                "vertex_offset": vertex_offset,
                "face_offset": face_offset,
                "vertex_count": len(verts),
                "triangle_count": len(faces),
                "bbox_min_mm": bbox_min.tolist(),
                "bbox_max_mm": bbox_max.tolist(),
                "tris_full_at_source": len(faces),
            }
            new_disc_structures.append(struct)

            vertex_offset += len(verts)
            face_offset += len(faces)

        # Finalize consolidated mesh
        if all_vertices and all_faces:
            consolidated_verts = np.vstack(all_vertices)
            consolidated_faces = np.vstack(all_faces)

        # Save updated mesh and manifest
        write_mesh_binary(subject_dir, consolidated_verts, consolidated_faces)
        print(f"  Wrote mesh: {len(consolidated_verts)} vertices, {len(consolidated_faces)} faces")

        manifest["structures"].extend(new_disc_structures)
        manifest["vertex_count"] = len(consolidated_verts)
        manifest["triangle_count"] = len(consolidated_faces)
        manifest["bbox_min_mm"] = consolidated_verts.min(axis=0).tolist()
        manifest["bbox_max_mm"] = consolidated_verts.max(axis=0).tolist()

        save_manifest(subject, manifest)
        print(f"  Updated manifest: {len(manifest['structures'])} total structures")

    print("\nIngest complete. Re-export viewer bundles now:")
    print("  python3 scripts/export_viewer_bundle.py --subject ct_vhm -o build/viewer_male --budget-scale 0.85")
    print("  python3 scripts/export_viewer_bundle.py --subject ct_vhf -o build/viewer_female --budget-scale 0.85")

    return 0


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("command", choices=["ingest"], help="Command to run")

    args = parser.parse_args()

    if args.command == "ingest":
        return cmd_ingest(args)

    return 0


if __name__ == "__main__":
    sys.exit(main())
