#!/usr/bin/env python3
"""Ingest generated rib articulation OBJ files into the atlas bundles.

This script:
1. Reads OBJ files generated by generate_rib_articulations.py
2. Loads existing manifests for ct_vhm and ct_vhf
3. Reconstructs mesh by adding articulation geometry to existing structures
4. Updates manifests with proper vertex/triangle offsets
5. Exports bundles back to binary format
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

OUTPUT_DIR = REPO_ROOT / "data" / "ct_sources" / "task_outputs"
BUILD_DIR = REPO_ROOT / "build" / "vh"


def read_obj_file(filepath: Path) -> tuple[np.ndarray, np.ndarray]:
    """Read OBJ file and return vertices and faces."""
    vertices = []
    faces = []

    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue

            parts = line.split()
            if not parts:
                continue

            if parts[0] == 'v':  # Vertex
                v = [float(parts[1]), float(parts[2]), float(parts[3])]
                vertices.append(v)
            elif parts[0] == 'f':  # Face
                face_indices = []
                for part in parts[1:]:
                    v_idx = int(part.split('/')[0]) - 1
                    face_indices.append(v_idx)

                for i in range(1, len(face_indices) - 1):
                    faces.append([face_indices[0], face_indices[i], face_indices[i + 1]])

    return np.array(vertices), np.array(faces)


def read_mesh_binary(subject_dir: Path) -> tuple[np.ndarray, np.ndarray]:
    """Read existing mesh from binary files."""
    verts_file = subject_dir / "vertices.f32"
    faces_file = subject_dir / "faces.u32"

    if not verts_file.exists() or not faces_file.exists():
        return np.empty((0, 3)), np.empty((0, 3), dtype=np.uint32)

    verts = np.fromfile(verts_file, dtype=np.float32).reshape(-1, 3)
    faces = np.fromfile(faces_file, dtype=np.uint32).reshape(-1, 3)

    return verts, faces


def write_mesh_binary(subject_dir: Path, vertices: np.ndarray, faces: np.ndarray) -> None:
    """Write mesh to binary files."""
    vertices.astype(np.float32).tofile(subject_dir / "vertices.f32")
    faces.astype(np.uint32).tofile(subject_dir / "faces.u32")


def load_manifest(subject: str) -> dict:
    """Load manifest for a subject."""
    manifest_path = BUILD_DIR / subject / "manifest.json"
    with open(manifest_path) as f:
        return json.load(f)


def save_manifest(subject: str, manifest: dict) -> None:
    """Save manifest for a subject."""
    manifest_path = BUILD_DIR / subject / "manifest.json"
    with open(manifest_path, 'w') as f:
        json.dump(manifest, f, indent=2)


def cmd_ingest(args: argparse.Namespace) -> int:
    """Ingest articulation OBJ files into bundles."""

    for subject in ["ct_vhm", "ct_vhf"]:
        print(f"\nIngesting rib articulations for {subject}...")
        subject_dir = BUILD_DIR / subject

        # Load manifest and existing mesh
        manifest = load_manifest(subject)
        existing_verts, existing_faces = read_mesh_binary(subject_dir)

        print(f"  Current mesh: {len(existing_verts)} vertices, {len(existing_faces)} faces")
        print(f"  Current structures: {len(manifest['structures'])}")

        # Load articulation OBJ files
        articulation_meshes = {}
        for obj_file in sorted(OUTPUT_DIR.glob(f"{subject}_*_articulation_*.obj")):
            stem = obj_file.stem
            atlas_id = stem.replace(f"{subject}_", "")

            try:
                verts, faces = read_obj_file(obj_file)
                articulation_meshes[atlas_id] = (verts, faces)
            except Exception as e:
                print(f"  Error loading {obj_file.name}: {e}")
                continue

        if not articulation_meshes:
            print(f"  No articulation files found for {subject}")
            continue

        print(f"  Loaded {len(articulation_meshes)} new articulation structures")

        # Consolidate all existing geometry + new articulations
        all_vertices = [existing_verts] if len(existing_verts) > 0 else []
        all_faces = [existing_faces] if len(existing_faces) > 0 else []

        vertex_offset = len(existing_verts)
        face_offset = len(existing_faces)

        # Add articulation structures to manifest
        new_articulation_structures = []

        for atlas_id in sorted(articulation_meshes.keys()):
            verts, faces = articulation_meshes[atlas_id]

            # Compute bounding box
            bbox_min = verts.min(axis=0)
            bbox_max = verts.max(axis=0)

            # Add to consolidation
            all_vertices.append(verts)
            all_faces.append(faces)

            # Determine side from atlas_id (sternal_articulation_l01 -> left, r01 -> right)
            side_char = atlas_id.split('_')[-1][0]  # Get 'l' or 'r'
            side = "left" if side_char == 'l' else "right"

            # Create structure entry
            struct = {
                "atlas_id": atlas_id,
                "source_structure": atlas_id,
                "side": side,
                "source_file": f"generated by generate_rib_articulations.py#{atlas_id}",
                "vertex_offset": vertex_offset,
                "face_offset": face_offset,
                "vertex_count": len(verts),
                "triangle_count": len(faces),
                "bbox_min_mm": bbox_min.tolist(),
                "bbox_max_mm": bbox_max.tolist(),
            }

            manifest["structures"].append(struct)
            new_articulation_structures.append(struct)

            vertex_offset += len(verts)
            face_offset += len(faces)

        # Write consolidated mesh
        if all_vertices:
            consolidated_verts = np.vstack(all_vertices)
            consolidated_faces = np.vstack(all_faces)
        else:
            consolidated_verts = np.empty((0, 3), dtype=np.float32)
            consolidated_faces = np.empty((0, 3), dtype=np.uint32)

        print(f"  Writing consolidated mesh: {len(consolidated_verts)} vertices, {len(consolidated_faces)} faces")
        write_mesh_binary(subject_dir, consolidated_verts, consolidated_faces)

        # Save updated manifest
        save_manifest(subject, manifest)
        print(f"  Updated manifest with {len(new_articulation_structures)} articulation structures")

        # Export bundles back to OBJ for verification
        print(f"  Exporting bundle to OBJ for verification...")
        export_bundle_to_obj(subject)

    return 0


def export_bundle_to_obj(subject: str) -> None:
    """Export bundle to OBJ file for verification."""
    subject_dir = BUILD_DIR / subject
    manifest = load_manifest(subject)

    # Read mesh
    verts, faces = read_mesh_binary(subject_dir)

    # Write to OBJ
    output_path = subject_dir / f"{subject}_with_articulations.obj"
    with open(output_path, 'w') as f:
        f.write(f"# {subject} with rib articulations\n\n")
        for v in verts:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
        f.write("\n")
        for face in faces:
            f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")

    print(f"  Exported to {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "command",
        choices=["ingest"],
        help="Command to run",
    )

    args = parser.parse_args()

    if args.command == "ingest":
        return cmd_ingest(args)

    return 0


if __name__ == "__main__":
    sys.exit(main())
